# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

tasks:

  test:
    cmds:
    - for: ["geojson", "ogc", "stac"]
      cmd: |
        uv run \
        --no-cache \
        --with cwltool \
        cwltool \
        --verbose \
        --validate \
        ./test/{{.ITEM}}.cwl

  generate_schema:
    internal: true
    cmds:
    - |
      uv run \
      --no-cache \
      --with json-schema2salad \
      json-schema2salad \
      --output {{.OUTPUT}} \
      {{.SCHEMAS}}
    - schema-salad-tool --print-pre {{.OUTPUT}} | yq -P

  generate_schemas:
    cmds:
    - for:
      - '1.0.0'
      - '1.1.0'
      task: generate_schema
      vars:
        SCHEMAS: 'https://schemas.stacspec.org/v{{ .ITEM }}/item-spec/json-schema/item.json https://schemas.stacspec.org/v{{ .ITEM }}/collection-spec/json-schema/collection.json https://schemas.stacspec.org/v{{ .ITEM }}/catalog-spec/json-schema/catalog.json'
        OUTPUT: 'stac_v{{ .ITEM }}.yaml'
    - task: generate_schema
      vars:
        SCHEMAS: 'https://geojson.org/schema/Geometry.json https://geojson.org/schema/Feature.json https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/featureCollectionGeoJSON.yaml'
        OUTPUT: 'geojson.yaml'

  generate_schema_doc:
    internal: true
    cmds:
    - mkdir -p ./docs/{{ .TARGET }}
    - |
       uv run \
       --no-cache \
       --with schema-salad \
       schema-salad-doc \
       ./{{ .SCHEMA }}.yaml > ./docs/{{ .TARGET }}/schema.html

  generate_schemas_doc:
    cmds:
    - task: generate_schema_doc
      vars:
        SCHEMA: 'geojson'
        TARGET: 'geojson'
    - task: generate_schema_doc
      vars:
        SCHEMA: 'ogc'
        TARGET: 'ogc'
    - task: generate_schema_doc
      vars:
        SCHEMA: 'stac_v1.0.0'
        TARGET: 'stac/1.0.0'
    - task: generate_schema_doc
      vars:
        SCHEMA: 'stac_v1.1.0'
        TARGET: 'stac/1.1.0'
    - task: generate_schema_doc
      vars:
        SCHEMA: 'string_format'
        TARGET: 'string-format'
