# EOAP Schemas (c) 2024-2025
# 
# EOAP Schemas is licensed under
# Creative Commons Attribution-ShareAlike 4.0 International.
#
# You should have received a copy of the license along with this work.
# If not, see <https://creativecommons.org/licenses/by-sa/4.0/>.

version: '3'

tasks:

  conditional-pip-install:
    internal: true
    status:
    - command -v {{.LIB}}
    cmds:
    - pip install {{.LIB}}

  test:
    deps:
    - task: conditional-pip-install
      vars:
        COMMAND: cwltool
    cmds:
    - for: ["geojson", "ogc", "stac"]
      cmd: cwltool --verbose --validate ./test/{{.ITEM}}.cwl
